<?php
/*
 * This file is part of the NB Framework package.
 *
 * Copyright (c) 2018 https://nb.cx All rights reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace util;

use nb\Config;
use nb\Debug;
use nb\Request;
use nb\Response;
use nb\Session;

/**
 * Admin
 *
 * @package util
 * @link https://nb.cx
 * @author: collin <collin@nb.cx>
 * @date: 2018/8/9
 */
class Admin extends Controller {

    //验证器
    public $_validate = Validate::class;

    public function __before() {
        $conf = Config::$o;
        $this->assign('conf',$conf);

        //验证是否登陆
        $auth = Auth::init();
        if($auth->islogout) {
            redirect('/login');
            return false;
        }

        //登陆信息传递给模版
        $this->assign('auth',$auth);
        return true;
    }

    //验证地址是否安全
    protected function protect($func=null) {
        $func or $func = function (){
            $this->back('非法请求');
        };
        Security::protect($func);
    }

    /**
     * 添加一个信息提示
     * @param $content
     * @param string $title
     * @param string $status
     */
    protected function alert($content,$title='Have errer!',$status='success') {
        $alert = Session::get('alert')?:[];
        $alert[] = [
            'status'=>$status,
            'title'=>$title,
            'content'=>$content
        ];
        Session::set('alert',$alert);
    }

    protected function look($url,$name) {
        $this->alert('操作成功！前往查看<a target="_blank" href="'.$url.'">'.$name.'</a>');
    }

    /**
     * 返回上一面，并可给出提示信息
     * @param null $msg
     */
    protected function back($msg = null) {
        if($msg) {
            $alert = Session::get('alert')?:[];
            $alert[] = [
                'status'=>'success',
                'title'=>'Have errer!',
                'content'=>$msg
            ];
            Session::set('alert',$alert);
        }
        Response::header('Location',Request::driver()->referer);
        Debug::quit();
    }

    /**
     * 重定向并提示
     * @param $url
     * @param null $msg
     */
    protected function redirect($url=null,$msg=null,$status='success') {
        $msg and $this->alert($msg);
        $url or $url = Request::driver()->referer;
        redirect($url);
    }

    protected function display($template = '', $vars = [], $config = []) {
        $alert = Session::pull('alert');
        $data = '';
        if($alert) {
            $file = __APP__.Config::$o->folder_app.DS.'view'.DS.'alert.html';
            $file = file_get_contents($file);

            foreach ($alert as $v) {
                $data .= sprintf($file,$v['status'],$v['title'],$v['content']);
            }
        }

        $this->assign('alert',$data);

        parent::display($template, $vars, $config); // TODO: Change the autogenerated stub
    }


}