<?php
/*
 * This file is part of the NB Framework package.
 *
 * Copyright (c) 2018 https://nb.cx All rights reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace event;

use nb\Config;
use nb\event\Framework as Frame;
/**
 *
 * User: Collin
 * QQ: 1169986
 * Date: 17/12/2 下午4:46
 */
class Framework extends Frame {

    public function error($e,$deadly = false) {
        return true;
        echo $e->getFile().':'.$e->getLine()."\n";
        echo $e->getMessage()."\n";
        return false;
    }

    public function notfound() {
        //e(php_sapi_name());
        //e(Config::$o->sapi);
        //ed($_SERVER);
        return parent::notfound(); // TODO: Change the autogenerated stub
    }
}